config/routes.rb
Rails.application.routes.draw do
  resources :cards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :attack_name, presence: true
  validates :damages, presence: true
  validates :action, presence: true
  validates :image_card, presence: true
  validates :pv, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @term = params[:term]
    @cards = @term.blank? ? Card.all
                          : Card.where("name LIKE (?)","%#{@term}%")
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "La carte à été crée avec succès." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "La carte à été modifiée avec succès." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "La carte à été supprimée avec succès." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :description, :damages, :image_card, :pv, :action, :attack_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="card col-lg-12" id="<%= dom_id card %>" >

<div>

  <p class="health">

    <%= card.pv %>
  </p>

  <img class="card-img-top " src="<%= card.image_card %>" alt="illustration de la carte"  height="280px" >

</div>



<p>
  <h4><%= card.name %></h4>
</p>

<p class="top_card">
  <%= card.description %>
</p>


  <div class="top_card">



  <div class="top_card">
    <p>
    <strong><%= card.attack_name %></strong>


    </p>



  </div>
    <p>
      <strong><%= card.damages %></strong>

    </p>
  </div>


    <p class="top_card">
      <%= card.action %>
    </p>

</div>

app/views/cards/_form.html.erb
  <%= form_with(model: card) do |form| %>
    <% if card.errors.any? %>
      <div class="container"> style="color: red">
        <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

        <ul>
          <% card.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>



    <div class="formulaire">


    <h2>Crée ta propre carte !</h2>

      <div class="form_align">

        <%= form.text_field :name , placeholder: "Nom" %>

        <%= form.text_field :pv, placeholder: "pv" %>

      </div>


      <%= form.text_area :image_card, placeholder: "url image" %>


      <%= form.text_area :description, placeholder: "description" %>


      <div class="form_align">

        <%= form.text_field :attack_name, placeholder: "nom de l'attaque" %>


        <%= form.text_field :damages, placeholder: "Dégats" %>

      </div>

      <%= form.text_area :action, placeholder: "action effectuée" %>

    </div>




    <div class="container">
      <%=  form.submit  %>
    </div>




  <% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<div class="form_edit">

  <%= render "form", card: @card %>

</div>
<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">

  <h2>C'est quoi les Duckmons</h2>

  <div class="presentation">

    <p>
    Dans un monde fantastique appelé, Ducklandia, une légende raconte l'histoire des Duckmons,
    de puissantes créatures dotées de pouvoirs magiques. Ces Duckmons sont les gardiens de la paix
    et de l'équilibre dans Ducklandia. De tout type et de toutes taille, ils s’engagent dans des batailles
    épiques pour chaque miette de pain symbole de richesse et de survie dans ce monde. Tout commença par
    la découverte d’une terre cachée l’intérieur d’une montagne. Cette terre avait une météo propre et le plus
    intéressant se trouvait en ce qui l’habitait. Des êtres, rapidement appelés des duckmons le peuplait. Ils
    avaient des capacités encore inconnues par les êtres humains, ils étaient capables de cracher du feu, former
    des boules d’eau ou encore d’envoûter d’autre créature. Très rapidement, les aventuriers du monde entier se
    lassèrent à' leur poursuite pour en apprendre le plus possible et de découvrir de potentiels trésors cachés.
    </p>

    <%= image_tag "pres_duck.png" %>

  </div>

  <h2>Le Pokeduck</h2>

  <form class="search_bar" target="" method="">
  <div class="input-group mb-3">
    <input name="term" value="<%= @term %>" type="text" class="form-control" placeholder="Rechercher" aria-label="Rechercher" aria-describedby="basic-addon2">
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" type="submit">Rechercher</button>
    </div>
  </div>
</form>

  <%= link_to "Créer une carte", new_card_path, class: "btn btn-primary btn_create" %>


  <div class="row">
  <% @cards.each do |card| %>
    <div class="col-lg-4">
      <%= link_to card_path(card), class: "card-link" do %>
        <%= render card %>
        <div class="card-body card_button_show">

        </div>
      <% end %>
    </div>
  <% end %>
</div>

</div>

app/views/cards/new.html.erb
<div class="form_content">



  <div class="form_content_left">

    <%= render "form", card: @card %>

  </div>



  <div class="form_content_right">

    <h2>Exemple</h2>

    <%= image_tag "example.png", class: "carte_exemple" %>


  </div>







</div>

<%= link_to "retour aux cartes", cards_path, class: "return"%>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>


<h1><%= @card.name %></h1>

<div class="container col-lg-4">

  <div>
    <%= render @card %>
  </div>

  <div class="btn_control_show col-lg-8">
    <%= link_to "Modifier la carte", edit_card_path(@card), class:"btn btn-warning" %>
    <%= button_to "supprimer", @card, method: :delete, class:"btn btn-danger " %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Duckdoc</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header >

    <div class="header_left">

    <%= image_tag "logo_duckdoc.png", class: "logo" %>

    <div>
      <%= image_tag "logo_card.png", class: "nav_images" %>
      <a href="/cards">Cartes</a>
    </div>
    <div>
      <%= image_tag "logo_plus.png", class: "nav_images" %>
      <a href="/cards/new">Créer</a>
    </div>


    </div>

    <h1>Duckmons</h1>

  </header>

  <body>



    <%= yield %>
  </body>

  <footer>

    <div class="nav_footer">
      <a class="test" href="#haut">Retour en haut</a>
      <a href="/cards/new">Créer</a>
      <a href="/cards">Cartes</a>
    </div>

    <div class="social_media">
      <a href="https://twitter.com/Duckmons"><%= image_tag "twitter.png", class: "footer_images" %></a>
      <a href="https://www.instagram.com/duckmons/"><%= image_tag "instagram.png", class: "footer_images" %></a>
      <a href="mailto:duckmon161@gmail.com"><%= image_tag "enveloppe.png", class: "footer_images" %></a>
    </div>

    <%= image_tag "logo_duckdoc.png", class: "logo_footer" %>

  </footer>

</html>